spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: auth
              uri: lb://auth-api
              predicates:
                - Path=/auth/**

            - id: trade
              uri: lb://trade-api
              predicates:
                - Path=/trade/**

            - id: asset-websocket-api
              uri: lb:ws://asset-websocket-api
              predicates:
                - Path=/asset-ws/**
              filters:
                - StripPrefix=1
