# @name demo-order
GET http://127.0.0.1:8080/order/orders
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJ0ZXN0MUBleGFtcGxlLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzYyMDk3MzI3LCJleHAiOjE3NjIwOTc2Mjd9.VEj13oyCHikhO2Da9zny9MrY1MNjbvyIgremzfCvQuc
X-Request-Id: 12345

